export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_FAIL = "GET_BLOGS_FAIL";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAIL = "GET_BLOG_FAIL";
export const GET_BLOG_IMAGE_SUCCESS = "GET_BLOG_IMAGE_SUCCESS";
export const GET_BLOG_IMAGE_FAIL = "GET_BLOG_IMAGE_FAIL";
